CMS_OAUTH2_SECRET: mJfHgNe0YXLjWfNK239ygdKm
ID: IEYQe0PEJnYmAFzMX5A9gUxi
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAx464YnC/I3JZEXb4+Tm66Xhju/rLpNPIvdlNE/OpTl4Y4yRz

  jka/NcLUHjT9OWtjHOHjUm+jRUglJPvodGXnmszCvEDsRzYkZWhwKOjuo7MQ1o/V

  eO/DrHuE/BH3rDu6CVDoRvz+bfrBX5fFyO1N3KYuPpj4WH5vzrT0xEGpQilijMLv

  Oi50MzoLT+m5JR579WeS/h9+qPuwD0SI9HIFP1oc8lme+7vFnynZsdMbKfgDPR5b

  HXlUkb3HEV0LMIw9IckcCzbt4qA2qEF/dzPsB670wUUhkwDKAhBR5FPMvo77HN3T

  fgMLglOBSAHt2Gm93OWaA24iio70nj+K/2ezAQIDAQABAoIBADgpqioGWjzzJy8b

  oTmfLkQb/lG+5UZn1mTb/e3iEyG7qNxwe1ctAQ5z3Tf9KNFasEPGLTCbu8M5aT7N

  6N+teG/gNeQ+j2EBU1/48ywIVnVa5Z/FTkqhjBwEjWpV8jMWgiayDxU/ianRO1AY

  inEgnFu/p181tRtOxk/SLNr5MdYtCI/9Mdsf8AvKIV9QRuGGjvXycXlerFaqCnue

  mobZdG35ZJJyLfr2gAhVMjxZhFWbIhpmMFROyCiH+J/ZHK27xjsa5/+3sUXpyofe

  8ZET4iTsRVwEjKSpizlH/W+SCIUJXBest0rgompRZMPMH5lLQ4q/t8rCSThHBd2/

  wRiKU1MCgYEAympJf+Oq+//uioiPhAgnxzJEqnyrOv+9BLzICPfcO4frzry77XnQ

  iWoORbtat0yRWRMCYcCBYijip3b2R/VIofrfHzQjPNNOOTRCc81Tpp51J2puJjFn

  TOpfoqTmZxSbqEhnvSYRXE+S6MQFYOp8Bpl9worbhcnoDiKCPM3U9QcCgYEA/GLE

  eDIP3XDpEUroK8Zl80Z8ciFWNJVUVUKif/r5sET9eL7N3r0deNXXv36/1QeKIXxj

  wzLUM2cgS+4D2aRd+HqyENh/NYm49KpHfYfPQHc3rLReLgDyfguzyJrPa2/Pn64b

  pilPX6tlOBXToNj8gbkZmHcmIzdN4d8g9I5PXbcCgYBySgkuGNKWby+1MN434pLz

  OkLjMHlOWs/TOPSJe8nyIxDWLmK996XzsNpWLS9PiAAZl04k+5kSX5t6iwUMJEba

  jtgkuj+bPIRScFuFH044KghkNQf0sLhvCXbuUsV1NoGdRySr/C6ZPKTqoKOY0U0u

  PMRxcA37QMGyGXIH+wBfSQKBgQClOKczpFo8dgktt+LrnVLqgo8/S9GaVNPDiP7G

  V2+T1GY24Hn3QciEbUFy7C/67pefukW46JKAIBfFfUhp9y9JVlExs/j6/HDnQn3Q

  kNK9eg4pcl5hMV+N4m1MewQkair6dslE6rA6igKWR7umBcavyZQW+pEt5quGnUJ+

  tpcAWwKBgQCziTE58bYAIJxryqRo1c45F8iwIPCCfIGroTBeOcsUK7+0nRBXeA3x

  FoYOEuVvYFcarFENvhtaDsxnMoxwOsCnBTckhqZbrZtTwuLkJZ2Rdfe+YpmqzbMO

  3nPxErlMpoCFIz5y/8iWK3Pgx0QuHVmwpXFkdbLzc2KNrZY9Ep2Rzw==

  -----END RSA PRIVATE KEY-----'
MYSQL_ROOT_PASSWORD: bvIazwZL
OPENEDX_MYSQL_PASSWORD: 0XgD9HG2
OPENEDX_SECRET_KEY: C6Pvij84IIpKpXlht0YEMnC0
PLUGINS:
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
